export { default as Chat } from './Chat'
export { default as Img } from './Img'
export { default as Face } from './Face'
export { default as Contact } from './Contact'
export { default as Instructions } from './Instructions'